---
output:
  md_document:
    variant: markdown_github
bibliography: bibliography.bib
---

---
bibliography: references.bib
---

# ImbRegSamp

Sampling methods for imbalanced regression. Implemented resampling methods are:

1- [SMOTER](https://link.springer.com/chapter/10.1007/978-3-642-40669-0_33) [@10.1007/978-3-642-40669-0_33]

2- [SMOGN](https://proceedings.mlr.press/v74/branco17a) [@pmlr-v74-branco17a]

3- Random over-under sampling

4- WERSC [@BRANCO201976]

5- GNO (Gaussian Noise Oversampling) [@BRANCO201976]

6- GSMOTER (Geometric SMOTE for Regression) [@CAMACHO2022116387]

7- SMOTERWB (SMOTER with Boosting)

Implemented metrics are:

1- WSSE (weighted sum of squared error)

2- WMSE (weighted mean squared error)

3- WMAD (weighted mean absolute deviation)

4- WMAPE (weighted mean absolute percentage error)

5- MU (Mean utility scores) [@torgo2007utility]

6- NMU (Normalized mean utility scores) [@torgo2007utility]

7- Precision for regression [@torgo2007utility]

8- Recall for regression [@torgo2007utility]

9- $F_\beta$ for regression [@torgo2007utility]

Implemented relevance functions are:

1- PCHIP (Piecewise Cubic Hermite Interpolating Polynomials) [@torgo2007utility]

2- [Inverse Kernel Density Estimation](https://link.springer.com/article/10.1007/s10994-021-06023-5) [@steininger2021]

3- Sigmoid relevance [@torgo2009precision]

More methods will be added.

# R installation

devtools::install_github("<https://github.com/fatihsaglam/ImbRegSamp>")

# References
